name: Domain Validation
description: Automatically peform Domain Control Validation for Certificate Authorities using DNS. Currently supporting Entrust.
author: vanbroup
branding:
  icon: 'refresh-cw'  
  color: 'purple'

inputs:
  DNS_PROVIDER: 
    description: Name of a DNS provider supported by http://github.com/go-acme/lego
    required: true
  DURATION_BEFORE_EXPIRY: 
    description: Re-validate domains that expire within this time from now, you can set multiple providers by using `DNS_PROVIDER_example_com` for each domain that doesn't use the default provider.
    default: 744h
    required: false

runs:
  using: 'docker'
  image: 'docker://docker.pkg.github.com/digitorus/dv/dv:latest'
  env:
    DNS_PROVIDER: ${{ inputs.DNS_PROVIDER }}
    DURATION_BEFORE_EXPIRY: ${{ inputs.DURATION_BEFORE_EXPIRY }}
