#!/bin/sh

git clone --depth 1 https://github.com/digitorus/dv.git /tmp/dv

# Create GitHub action inputs
grep -h -E '^\s+[A-Z0-9]+(_[A-Z0-9])+' /tmp/dv/providers/**/*.toml | sort -b -u -k1,1 | awk '{split($0,a,"="); printf "  %s:\n    description: %s\n    required: false\n", $1, a[2]}' > /tmp/dv/settings.yml

# Create a list of environment variables for DNS providers
grep -h -E '^\s+[A-Z0-9]+(_[A-Z0-9])+' /tmp/dv/providers/**/*.toml | sort -b -u -k1,1 | awk '{printf "    %s: ${{ inputs.%s }}\n", $1, $1}' > /tmp/dv/env.yml

rm -f action.yml
echo "# DO NOT EDIT; Generated by update.sh; Update action-template.yml instead" > action.yml
cat action-template.yml >> action.yml

sed -i -e "/^#--SETTINGS--/r /tmp/dv/settings.yml" -e "//d" action.yml
sed -i -e "/^#--ENV--/r /tmp/dv/env.yml" -e "//d" action.yml

rm -rf /tmp/dv