name: Update Action Config

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * 3'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Sync action config with providers
        run: |
          ./update.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@6bb739433928fbc2bdc635d41105e124d0dce021
        with:
          title: Sync GitHub Action config with DNS providers
          body: |
            Sync GitHub Action config with options supported by DNS providers in https://github.com/EntrustCorporation/dv
          labels: config, automated pr
          commit-message: Sync GitHub Action config with DNS providers
          branch: auto-update-action-config
          delete-branch: true
