name: Update Action Config

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * 3'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Update Action config
        run: |
          ./update.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Update Action config
          labels: config, automated pr
